name: Reusable MkDocs Deploy

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory containing the MkDocs project'
        type: string
        default: '.'
      python-version:
        description: 'Python version to use'
        type: string
        default: '3.11'
      poetry-install-args:
        description: 'Additional arguments for poetry install'
        type: string
        default: '--with docs'
      deploy:
        description: 'Whether to deploy to GitHub Pages or just build'
        type: boolean
        default: false

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: fetch all history for mike
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      
      - name: Install dependencies
        run: poetry install ${{ inputs.poetry-install-args }}
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get version
        id: get_version
        run: |
          version=$(poetry version -s)
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Build and deploy documentation
        if: inputs.deploy
        run: |
          # Initialize gh-pages branch if it doesn't exist
          git fetch origin gh-pages || git branch gh-pages
          # Deploy the new version and update aliases
          poetry run mike deploy --push --update-aliases ${{ steps.get_version.outputs.version }} latest
          poetry run mike set-default --push latest
        
      - name: Build documentation (no deploy)
        if: "!inputs.deploy"
        run: |
          poetry run mkdocs build --clean
          poetry run mike list